hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

jpa:
  label: JPA
  permalink: /jpa
  description: JPA tag description

spring:
  label: Spring
  permalink: /spring
  description: Spring tag description