hello:
  label: Hello
  permalink: /hello
  description: Hello tag description

jpa:
  label: JPA
  permalink: /jpa
  description: JPA tag description

spring:
  label: Spring
  permalink: /spring
  description: Spring tag description

mysql:
  label: MySQL
  permalink: /mysql
  description: MySQL tag description

redis:
  label: Redis
  permalink: /redis
  description: Redis tag description

kafka:
  label: Kafka
  permalink: /kafka
  description: Kafka tag description

open-telemetry:
  label: OpenTelemetry
  permalink: /open-telemetry
  description: OpenTelemetry tag description

system-design:
  label: SystemDesign
  permalink: /system-design
  description: SystemDesign tag description

architecture:
  label: Architecture
  permalink: /architecture
  description: Architecture tag description